name: Windows MSVC x64

on:
  push:
    branches:
      - master
      - cmakepresets
    paths-ignore:
      - '*.md'
      - 'docs/**'
  pull_request:
    types: [ opened, synchronize ]
    paths-ignore:
      - '*.md'
      - 'docs/**'

permissions:
  contents: write

env:
  VCPKG_FEATURE_FLAGS: dependencygraph
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v7
      with:
        fetch-depth: 0

    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2

    - name: Install latest CMake
      uses: lukka/get-cmake@latest

    - name: Restore or setup vcpkg
      uses: lukka/run-vcpkg@v11.6
      with:
        vcpkgGitCommitId: '40f3c709db80acf154ac4b17a1f83c564ebd022e'

    - name: Fetch test data
      run: |
          New-Item -ItemType Directory -Force -Path "build/msvc-x64-RelWithDebInfo"
          Invoke-WebRequest -Uri "https://github.com/diasurgical/devilutionx-assets/releases/download/v2/spawn.mpq" -OutFile "build/msvc-x64-RelWithDebInfo/spawn.mpq" -Resume

    - name: Run CMake consuming CMakePresets.json and vcpkg.json by mean of vcpkg.
      uses: lukka/run-cmake@v10
      with:
        configurePreset: 'msvc-x64-RelWithDebInfo'
        buildPreset: 'msvc-x64-RelWithDebInfo'
        testPreset: 'msvc-x64-RelWithDebInfo'
        configurePresetAdditionalArgs: '-DCMAKE_EXE_LINKER_FLAGS="/STACK:8388608" -DDISABLE_LTO=ON'

    - name: Upload-Package
      if: ${{ !env.ACT }}
      uses: actions/upload-artifact@v7
      with:
        name: devilutionx.exe
        path: |
            build/msvc-x64-RelWithDebInfo/devilutionx.exe
            build/msvc-x64-RelWithDebInfo/bz2.dll
            build/msvc-x64-RelWithDebInfo/discord_game_sdk.dll
            build/msvc-x64-RelWithDebInfo/libpng16.dll
            build/msvc-x64-RelWithDebInfo/libsodium.dll
            build/msvc-x64-RelWithDebInfo/lua.dll
            build/msvc-x64-RelWithDebInfo/SDL2.dll
            build/msvc-x64-RelWithDebInfo/SDL2_image.dll
            build/msvc-x64-RelWithDebInfo/z.dll
